In [1]:
import pandas as pd
from pycaret.regression import *
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

import os

In [2]:
currentpath = os.getcwd()
print(currentpath)

C:\Users\PC\OneDrive - 명지대학교\2023 방학 연구실 과제\Model

In [3]:
data = pd.read_csv('../변환 데이터/processing_const.csv')

data

         CH4   CO2   O2         Q     P     T   VOR
0       47.7  41.3  0.3  1.116667  76.0   4.0  25.0
1       41.3  36.3  0.3  0.800000  80.0   7.0  20.0
2       39.5  38.1  0.3  0.366667  43.0   6.0  15.0
3       53.5  43.6  0.2  0.716667  64.0   5.0  20.0
4       43.1  38.9  0.4  0.466667  41.0   5.0  15.0
...      ...   ...  ...       ...   ...   ...   ...
622768  33.5  33.6  0.1  0.483333  33.0  12.0  20.0
622769  35.8  33.9  0.4  0.066667  10.0  12.0  15.0
622770  34.2  33.6  0.3  0.066667  10.0  12.0  15.0
622771  33.6  33.5  0.3  0.083333  10.0  12.0  15.0
622772  34.9  33.2  0.3  0.116667  17.0  12.0  15.0

[622773 rows x 7 columns]

## Normalize = True (min-max)

In [4]:
s = setup(data = data,  # 사용 하는 데이터
            target = 'CH4',  
            
            normalize = True, # False
            normalize_method = 'minmax', # 기본은 zscore 
            
            transformation = True, # 데이터 샘플들의 분포가 정규분포에 더 가까워지도록 처리
            
            fold = 5, # 기본적으로 10 fold 로 training 한다.
            fold_shuffle=True,
            
#             ignore_features = ['PriceDiff'], # 제외할 컬럼 (이거 너무 편하다!)
#             numeric_features = ['PriceCH','PriceMM'],
#             categorical_features = ['Store7'], # 지정하면 onehotencoding된다. 
#             date_features = [], # 날짜 feature를 년월일시 로 바꿔서 onehotencoding 해준다. 
            
            silent = True, # setup 시 중간에 피쳐속성 확인하고 엔터 쳐줘야하는데 알아서 넘어가게 해준다.
           
            session_id = 123, # random state number 지정
            
            use_gpu = True, # gpu 사용 옵션
            
#             feature_selection = True,
#             feature_selection_method = 'classic', # or 'boruta' 
            # classic 은 permutation importance 기반이다.
            
#             fix_imbalance = True, # data imbalance 를 sampling method로 보정
#             fix_imbalance_method = imblearn.OverSampling.RandomOverSampler()
            # 기본은 SMOTE
            
            # custom_pipeline = pipe, preprocess =False 
            # 두 개는 세트, 사용자가 원하는 파이프라인을 구성할 수 있다. 
            
            )

In [5]:
# 제공되는 모델 중 성능을 DataFrame 형태로 출력
best = compare_models()